server:
  port: 8801  #端口号
spring:
  application:
    name: nacos-consumer1 #服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #Nacos server 的地址
#以下配置信息并不是默认配置，而是我们自定义的配置，目的是不在 Controller 内硬编码服务提供者的服务名
service-url:
  nacos-user-service: http://nacos-provider1    #服务提供者的服务名


